var EcommerceRepository=require('./EcommerceRepository');
var repository=new EcommerceRepository();
function EcommerceService(){
    this.register=function(newUser){
        repository.register(newUser);
    }
    this.authenticateUser=function(user,callback){
        repository.authenticateUser(user,(authenticationRes)=>{
            callback(authenticationRes);
        });
    }
    this.getMobiles=function(callback){
        repository.getMobiles((mobiles)=>{
           callback(mobiles);
    });
    }
    this.getBags=function(callback){
        repository.getBags((bags)=>{
           callback(bags);
    });
    }
    this.getLaptops=function(callback){
        repository.getLaptops((laptops)=>{
           callback(laptops);
    });
    }
    this.getCart=function(callback){
        repository.getCart((cart)=>{
           callback(cart);
    });
    }
    this.getCustomers=function(callback){
        repository.getCustomers((customers)=>{
           callback(customers);
    });
    }
    this.removeItem=function(no){
        repository.removeItem(no);
    }
    this.getCartItems=function(callback){
        repository.getCartItems((items)=>{
           callback(items);
    });
    }
    this.getCategories=function(callback){
        repository.getCategories((categories)=>{
           callback(categories);
    });
    }
    this.addToCart=function(lineitem,orgId,customerId){
        repository.addToCart(lineitem,orgId,customerId);
    }
    this.checkout=function(lineitem,customerId){
        repository.checkout(lineitem,customerId);
    }
}
module.exports=EcommerceService;